import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import "../styles.css";

export const Route = createFileRoute("/")({ component: Index });

const images={
 hero:"https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&fm=jpg&q=82&w=1300",
 activity:"https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&fm=jpg&q=82&w=1000",
 learning:"https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&fm=jpg&q=82&w=1000",
 parent:"https://images.unsplash.com/photo-1504159506876-f8338247a14a?auto=format&fit=crop&fm=jpg&q=82&w=1000"
};

function useScrollReveal(){
 useEffect(()=>{
  const items=[...document.querySelectorAll<HTMLElement>(".scroll-reveal")];
  const reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  if(reduce){items.forEach(x=>x.classList.add("in-view"));return;}
  const io=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle("in-view",e.isIntersecting)),{threshold:.16,rootMargin:"-10% 0px -10% 0px"});
  items.forEach(x=>io.observe(x)); return()=>io.disconnect();
 },[]);
}

function Index(){
 useScrollReveal();
 const [seconds,setSeconds]=useState(15*60);
 useEffect(()=>{const id=window.setInterval(()=>setSeconds(s=>s<=0?15*60:s-1),1000);return()=>window.clearInterval(id)},[]);
 const timer=String(Math.floor(seconds/60)).padStart(2,"0")+":"+String(seconds%60).padStart(2,"0");

 return <div className="nk">
  <header className="nav"><a className="brand" href="#home"><span className="logo-mark">🧠</span><span>Neuro Kids</span></a><a className="nav-cta" href="#pricing">Get Started</a></header>
  <main>
   <section id="home" className="hero reference-hero scroll-reveal"><div className="hero-copy"><span className="eyebrow coral">NEURO KIDS™ • AGES 4–12</span><h1>Fun activities that help kids <span>focus, think & learn.</span></h1><p className="lead">A playful, screen-free collection of brain-training activities designed to turn a few minutes a day into a positive learning routine.</p><div className="hero-bullets"><span>✓ Build attention & memory</span><span>✓ Practise logic & problem-solving</span><span>✓ Encourage creativity & confidence</span><span>✓ Simple 10–15 minute activities</span></div><div className="hero-actions"><a className="btn yellow" href="#pricing">Get Neuro Kids Today →</a><a className="text-btn" href="#inside">See what's inside ↓</a></div><div className="hero-note">Instant digital access • Printable activities • Screen-free play</div></div><div className="hero-visual"><div className="shape star">✦</div><img src={images.hero} alt="Child happily doing a colourful educational activity"/><div className="image-pill">🧠 Play • Focus • Grow</div></div></section>

   <section className="social-proof scroll-reveal"><div><strong>Made for busy parents & caregivers</strong><span className="stars">★★★★★</span><span>Simple activities children can actually enjoy</span></div></section>

   <section className="section pain scroll-reveal"><div className="section-head centered"><span className="eyebrow">THE EVERYDAY STRUGGLE</span><h2>What if learning could feel <span>easier?</span></h2><p>Neuro Kids is built around short, playful activities instead of long lessons or more screen time.</p></div><div className="pain-grid"><article><b>🎯</b><h3>Hard to stay focused?</h3><p>Give your child small challenges that invite them to notice, remember and complete.</p></article><article><b>📱</b><h3>Too much screen time?</h3><p>Swap a few minutes of scrolling for hands-on printable play that feels fresh.</p></article><article><b>😤</b><h3>“I can't do it” moments?</h3><p>Use approachable activities that celebrate effort, exploration and trying again.</p></article></div></section>

   <section id="inside" className="solution scroll-reveal"><div className="solution-image"><img src={images.activity} alt="Child solving a colourful puzzle activity"/></div><div className="solution-copy"><span className="eyebrow">INSIDE NEURO KIDS™</span><h2>One collection. <span>Many ways to play.</span></h2><p>Children can explore activities across the skills parents care about most, with variety that keeps the routine from feeling repetitive.</p><div className="check-list"><span>✓ Focus & attention activities</span><span>✓ Memory-building games</span><span>✓ Shapes, patterns & matching</span><span>✓ Logic & sequences</span><span>✓ Tracing & fine-motor practice</span><span>✓ Hand-eye coordination & creative challenges</span></div></div></section>

   <section className="section scroll-reveal"><div className="section-head centered"><span className="eyebrow">WHAT THEY PRACTISE</span><h2>Five core skills, <span>one playful routine.</span></h2></div><div className="benefit-grid">{[["🎯","Attention","Practise noticing details and staying with a task."],["🧠","Memory","Remember, match and connect information through games."],["🧩","Logic","Explore patterns, sequences and simple reasoning."],["💡","Problem-Solving","Try different approaches and discover solutions."],["🎨","Creativity","Make, imagine and express ideas through activities."],["⭐","Confidence","Build positive learning moments through achievable challenges."]].map(([i,t,p])=><article className="benefit-card scroll-reveal" key={t}><div className="benefit-icon">{i}</div><h3>{t}</h3><p>{p}</p></article>)}</div></section>

   <section className="how scroll-reveal"><div className="section-head centered"><span className="eyebrow">HOW IT WORKS</span><h2>From checkout to <span>play in minutes.</span></h2></div><div className="steps"><article className="step"><b>01</b><div className="step-icon">🛍️</div><h3>Choose your plan</h3><p>Pick Basic or Premium depending on how much activity variety you want.</p></article><article className="step"><b>02</b><div className="step-icon">⚡</div><h3>Get digital access</h3><p>Receive your access instructions after a successful purchase.</p></article><article className="step"><b>03</b><div className="step-icon">✏️</div><h3>Print & play</h3><p>Choose an activity, spend a few minutes together, and keep going at your own pace.</p></article></div><div className="week-preview"><div><span className="eyebrow">SAMPLE ROUTINE</span><h3>10–15 minutes can fit into the day.</h3></div><div className="week-days"><span>MON<br/><b>Memory</b></span><span>TUE<br/><b>Focus</b></span><span>WED<br/><b>Logic</b></span><span>THU<br/><b>Create</b></span><span>FRI<br/><b>Solve</b></span></div></div></section>

   <section className="reference-results section scroll-reveal"><div className="section-head centered"><span className="eyebrow">THE DIFFERENCE</span><h2>A simple way to create more <span>focused moments.</span></h2></div><div className="compare-grid"><div className="compare-card"><h3>WITH NEURO KIDS</h3><p>✓ Short, structured activities</p><p>✓ Screen-free practice</p><p>✓ Variety across thinking skills</p><p>✓ Easy to repeat at home</p><p>✓ Parent-friendly routine</p></div><div className="compare-card muted"><h3>WITHOUT A ROUTINE</h3><p>• Activities can feel random</p><p>• More time spent choosing what to do</p><p>• Harder to keep practice consistent</p><p>• Less variety from day to day</p><p>• Learning moments can be harder to plan</p></div></div></section>

   <section className="gallery section scroll-reveal"><div className="section-head centered"><span className="eyebrow">REAL-LIFE LEARNING MOMENTS</span><h2>Less scrolling. <span>More doing.</span></h2></div><div className="gallery-grid"><figure><img src={images.learning} alt="Children learning together at a table"/><figcaption>📚 Learn together</figcaption></figure><figure><img src={images.activity} alt="Child enjoying a puzzle"/><figcaption>🧩 Puzzle time</figcaption></figure><figure><img src={images.parent} alt="Parent helping a child learn"/><figcaption>💛 Parent & child</figcaption></figure></div></section>

   <section className="testimonials scroll-reveal"><div className="section-head centered"><span className="eyebrow">PARENT FEEDBACK</span><h2>Why families <span>love the routine.</span></h2><p className="sample-note">Sample testimonials for demonstration — replace with verified customer reviews before publishing.</p></div><div className="testimonial-grid">{[["Nandi","Cape Town","7","“The activities are short enough for our afternoons and my daughter enjoys choosing what to do next.”"],["Thabo","Johannesburg","5","“It gives us a simple screen-free activity after school. The variety makes it easy to keep things interesting.”"],["Lerato","Durban","9","“I like that I don't need a big setup. We can print an activity and get started together.”"]].map(([n,c,a,q])=><article className="testimonial scroll-reveal" key={n}><div>{n[0]}</div><div><strong>{n}</strong><small>{c} • Parent of a {a}-year-old</small></div><div className="stars">★★★★★</div><p>{q}</p></article>)}</div></section>

   <section id="pricing" className="pricing scroll-reveal"><div className="section-head centered"><span className="eyebrow">SPECIAL OFFER</span><h2>Start with Neuro Kids <span>today.</span></h2><p>Choose the collection that fits your family. Both options are digital and designed for easy at-home use.</p></div><div className="pricing-grid"><article id="checkout-basic" className="plan"><span className="plan-label">BASIC</span><h3>Neuro Kids Basic</h3><div className="price">R87</div><p>A focused starter collection.</p><ul><li>✓ 50+ brain-training exercises</li><li>✓ Focus & memory activities</li><li>✓ Logic & problem-solving</li><li>✓ Creativity activities</li><li>✓ Digital access</li></ul><a className="plan-btn" href="#checkout-basic">Get Basic — R87</a></article><article id="checkout-premium" className="plan popular"><div className="popular-badge">★ Most Popular / Best Value</div><span className="plan-label">PREMIUM</span><h3>Neuro Kids Premium</h3><div className="price">R109</div><p>The larger collection for more variety.</p><ul><li>✓ 300+ brain-training exercises in total</li><li>✓ Focus, memory & logic</li><li>✓ Problem-solving & creativity</li><li>✓ More activity variety</li><li>✓ Digital access</li></ul><a className="plan-btn yellow" href="#checkout-premium">Get Premium — R109 →</a></article></div><div className="countdown"><span>⏳ Special offer</span><strong>{timer}</strong><small>Timer is a visual offer element and resets after the countdown ends.</small></div><div className="payment-trust"><span>💳 Cards</span><span>⚡ Instant EFT</span><span>📲 SnapScan</span></div></section>

   <section className="section bonus-section scroll-reveal"><div className="section-head centered"><span className="eyebrow">MORE THAN A FEW WORKSHEETS</span><h2>Everything you need for <span>playful practice.</span></h2></div><div className="bonus-grid"><article><b>📘</b><h3>Printable activities</h3><p>Use the activities at home whenever a quick learning moment fits your day.</p></article><article><b>⚡</b><h3>Instant digital access</h3><p>No physical parcel to wait for. Access is delivered digitally after purchase.</p></article><article><b>♻️</b><h3>Repeatable practice</h3><p>Reuse favourite activities and create a routine that works for your child.</p></article><article><b>👨‍👩‍👧</b><h3>Parent-friendly</h3><p>Clear, approachable activities without needing special teaching experience.</p></article></div></section>

   <section className="guarantee section scroll-reveal"><div className="guarantee-card"><div className="guarantee-badge">7<br/><small>DAYS</small></div><div><span className="eyebrow">PEACE OF MIND</span><h2>7-day money-back guarantee</h2><p>You can request a refund within 7 days, subject to the applicable purchase terms. Please review the terms before checkout.</p></div></div></section>

   <section className="section faq scroll-reveal"><div className="section-head centered"><span className="eyebrow">FAQ</span><h2>Before you start, <span>here are the answers.</span></h2></div><div className="faq-list">{[["What age is Neuro Kids for?","The programme on this page is designed for children aged 4–12. Parents can choose activities that suit their child's age and current ability."],["How do I receive the product?","Neuro Kids is a digital product. After successful checkout, access instructions are provided digitally."],["Do I need teaching experience?","No. The activities are intended to be simple for parents and caregivers to set up and use."],["Does my child need a screen?","No. The activities are designed to be used away from screens once you have access to the digital materials."],["How much time should we spend each day?","A 10–15 minute routine is a practical starting point. You can adjust the pace to suit your child."],["What is the refund policy?","The page offers a 7-day money-back guarantee, subject to the applicable purchase terms and conditions."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>

   <section className="final-cta scroll-reveal"><div><span className="eyebrow">READY TO MAKE LEARNING PLAYFUL?</span><h2>Give your child more reasons to <span>think, explore and create.</span></h2><p>Start with a few minutes a day and make learning feel like something they want to do.</p><a className="btn yellow" href="#pricing">Choose Your Neuro Kids Plan →</a></div><div className="final-shape">✦ 🧠 ✦</div></section>
  </main>
  <footer><div><a className="brand" href="#home"><span className="logo-mark">🧠</span><span>Neuro Kids</span></a><p>Playful brain-training activities for growing minds.</p></div><div className="footer-links"><a href="#home">Home</a><a href="#inside">What's Inside</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a><a href="mailto:marcelomainato29@gmail.com">Contact</a></div><div className="socials"><a href="#home" aria-label="Facebook">f</a><a href="#home" aria-label="Instagram">◎</a><a href="#home" aria-label="TikTok">♪</a></div><div className="legal"><a href="#privacy">Privacy</a><a href="#terms">Terms</a><a href="mailto:marcelomainato29@gmail.com">marcelomainato29@gmail.com</a><span>© 2026 Neuro Kids. All rights reserved.</span></div></footer>
 </div>
}
